imports = ["./colors.toml"]

# Wayle configuration file
[bar]
scale = 0.699999988079071
bg = "transparent"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "separator",
    "dashboard",
    "separator",
    "separator",
    "window-title",
]
center = ["hyprland-workspaces"]
right = [
    "clock",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "notifications",
    "systray",
]

[styling]
theme-provider = "matugen"

[modules.hyprland-workspaces]
monitor-specific = false
app-icons-show = true

[modules.separator]
color = "transparent"

[modules.battery]
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"

[modules.bluetooth]
icon-bg-color = "accent"
label-color = "accent"

[modules.brightness]
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"

[modules.dashboard]
border-color = "border-accent"
icon-bg-color = "accent"

[modules.notifications]
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"

[modules.volume]
icon-bg-color = "accent"
label-color = "accent"

[modules.window-title]
border-color = "accent"
icon-bg-color = "border-accent"
label-color = "accent"

[wallpaper]
cycling-directory = "/home/haroonsyed/Pictures/"
cycling-interval-mins = 1
